version: '3'
services:
  db:
    container_name: api_db
    build: ./db
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: s3cr3tp4ssw0rd
    ports:
      - 5432:5432
  app:
    container_name: api
    build: ./
    command: ["go", "run", "main.go"]
    volumes:
      - .:/go/src/app
    ports:
      - "80:8080"
    depends_on:
      - db
    links:
      - db
